"""Encode and decode the compact binary OBC log record format.

The format is produced by ``obc/shared/logging/obc_logging_codec.h`` in the
firmware. File IDs are resolved through a versioned mapping generated by the
firmware build; the bundled mapping must be updated alongside firmware releases.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

SYNC_BYTE = 0xA8
FLAG_LEVEL_MASK = 0x07
FLAG_TYPE_MSG = 0x08
FLAG_HAS_TIMESTAMP = 0x10
FIXED_HEADER_SIZE = 6
TIMESTAMP_SIZE = 4
ERROR_CODE_SIZE = 4
MAX_MSG_LEN = 128
FILE_ID_UNKNOWN = 0xFFFF
LEVEL_NAMES = ("TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL")

_FILE_IDS_PATH = Path(__file__).with_name("log_file_ids.json")
_TEXT_LINE_RE = re.compile(
    r"^(?:(?P<dt>\d{2}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2})\s+|(?P<unix>\d+)\s+)?"
    r"(?P<level>TRACE|DEBUG|INFO|WARN|ERROR|FATAL)\s*->\s*"
    r"(?P<path>\S+):(?P<line>\d+)\s+-\s+(?P<payload>.*?)\s*$"
)
_file_paths: list[str] | None = None


class LogCodecError(Exception):
    """Raised when a binary record or a text log line is malformed."""


@dataclass
class LogEntry:
    """A decoded compact OBC log record."""

    level: int
    is_msg: bool
    file_id: int
    line: int
    timestamp: int | None = None
    err_code: int | None = None
    msg: str | None = None
    file_path: str | None = None

    @property
    def level_name(self) -> str:
        """Return the human-readable log level."""
        return LEVEL_NAMES[self.level]


def load_file_id_mapping(path: Path | str | None = None) -> list[str]:
    """Load a firmware-generated file-ID mapping, defaulting to the bundled one."""
    with open(path or _FILE_IDS_PATH) as mapping_file:
        data = json.load(mapping_file)
    return data["files"]


def _get_file_paths() -> list[str]:
    global _file_paths
    if _file_paths is None:
        _file_paths = load_file_id_mapping()
    return _file_paths


def file_path_from_id(file_id: int) -> str | None:
    """Resolve a file ID from the bundled firmware mapping."""
    paths = _get_file_paths()
    return paths[file_id] if 0 <= file_id < len(paths) else None


def file_id_from_path(path: str) -> int:
    """Resolve a source path from the bundled firmware mapping."""
    try:
        return _get_file_paths().index(path)
    except ValueError:
        return FILE_ID_UNKNOWN


def encode_log_entry(entry: LogEntry) -> bytes:
    """Encode a log entry into the firmware's compact binary wire format."""
    if not 0 <= entry.level < len(LEVEL_NAMES):
        raise LogCodecError(f"Invalid log level: {entry.level}")

    flags = entry.level
    if entry.is_msg:
        flags |= FLAG_TYPE_MSG
    if entry.timestamp is not None:
        flags |= FLAG_HAS_TIMESTAMP

    record = bytearray([SYNC_BYTE, flags])
    record += entry.file_id.to_bytes(2, "little")
    record += min(entry.line, 0xFFFF).to_bytes(2, "little")
    if entry.timestamp is not None:
        record += entry.timestamp.to_bytes(TIMESTAMP_SIZE, "little")
    if entry.is_msg:
        msg_bytes = (entry.msg or "").encode("utf-8")[:MAX_MSG_LEN]
        record.append(len(msg_bytes))
        record += msg_bytes
    else:
        record += (entry.err_code or 0).to_bytes(ERROR_CODE_SIZE, "little")
    return bytes(record)


def decode_log_entry(data: bytes, offset: int = 0) -> tuple[LogEntry, int]:
    """Decode one record at ``offset`` and return it with its consumed length."""
    remaining = len(data) - offset
    if remaining < FIXED_HEADER_SIZE:
        raise LogCodecError("Buffer too short for log record header")
    if data[offset] != SYNC_BYTE:
        raise LogCodecError(f"Bad sync byte: 0x{data[offset]:02X}")

    flags = data[offset + 1]
    level = flags & FLAG_LEVEL_MASK
    if level >= len(LEVEL_NAMES):
        raise LogCodecError(f"Invalid log level: {level}")

    is_msg = bool(flags & FLAG_TYPE_MSG)
    has_timestamp = bool(flags & FLAG_HAS_TIMESTAMP)
    file_id = int.from_bytes(data[offset + 2 : offset + 4], "little")
    line = int.from_bytes(data[offset + 4 : offset + 6], "little")
    consumed = FIXED_HEADER_SIZE
    timestamp = None
    if has_timestamp:
        if remaining < consumed + TIMESTAMP_SIZE:
            raise LogCodecError("Buffer too short for timestamp")
        timestamp = int.from_bytes(data[offset + consumed : offset + consumed + TIMESTAMP_SIZE], "little")
        consumed += TIMESTAMP_SIZE

    err_code = None
    msg = None
    if is_msg:
        if remaining < consumed + 1:
            raise LogCodecError("Buffer too short for message length")
        msg_len = data[offset + consumed]
        consumed += 1
        if msg_len > MAX_MSG_LEN or remaining < consumed + msg_len:
            raise LogCodecError("Buffer too short for message body")
        msg = data[offset + consumed : offset + consumed + msg_len].decode("utf-8", errors="replace")
        consumed += msg_len
    else:
        if remaining < consumed + ERROR_CODE_SIZE:
            raise LogCodecError("Buffer too short for error code")
        err_code = int.from_bytes(data[offset + consumed : offset + consumed + ERROR_CODE_SIZE], "little")
        consumed += ERROR_CODE_SIZE

    return (
        LogEntry(
            level=level,
            is_msg=is_msg,
            file_id=file_id,
            line=line,
            timestamp=timestamp,
            err_code=err_code,
            msg=msg,
            file_path=file_path_from_id(file_id),
        ),
        consumed,
    )


def decode_log_stream(data: bytes) -> list[LogEntry]:
    """Decode a stream, resynchronizing after malformed bytes or records."""
    entries: list[LogEntry] = []
    offset = 0
    while offset < len(data):
        if data[offset] != SYNC_BYTE:
            offset += 1
            continue
        try:
            entry, consumed = decode_log_entry(data, offset)
        except LogCodecError:
            offset += 1
            continue
        entries.append(entry)
        offset += consumed
    return entries


def entry_to_text(entry: LogEntry, unix_style: bool = False) -> str:
    """Render a decoded entry in the firmware's legacy text-log format."""
    path = entry.file_path or file_path_from_id(entry.file_id) or f"<file:{entry.file_id}>"
    payload = entry.msg if entry.is_msg else str(entry.err_code)
    prefix = ""
    if entry.timestamp is not None:
        if unix_style:
            prefix = f"{entry.timestamp} "
        else:
            timestamp = datetime.fromtimestamp(entry.timestamp, tz=timezone.utc)
            prefix = timestamp.strftime("%y-%m-%d_%H-%M-%S ")
    return f"{prefix}{entry.level_name:<5} -> {path}:{entry.line} - {payload}"


def parse_text_log_line(line: str) -> LogEntry:
    """Parse a firmware text-log line into a compact-log entry."""
    match = _TEXT_LINE_RE.match(line.strip())
    if match is None:
        raise LogCodecError(f"Unparseable log line: {line!r}")
    if match["dt"] is not None:
        timestamp = int(datetime.strptime(match["dt"], "%y-%m-%d_%H-%M-%S").replace(tzinfo=timezone.utc).timestamp())
    elif match["unix"] is not None:
        timestamp = int(match["unix"])
    else:
        timestamp = None
    payload = match["payload"]
    is_msg = not payload.isdigit()
    path = match["path"]
    return LogEntry(
        level=LEVEL_NAMES.index(match["level"]),
        is_msg=is_msg,
        file_id=file_id_from_path(path),
        line=int(match["line"]),
        timestamp=timestamp,
        err_code=None if is_msg else int(payload),
        msg=payload if is_msg else None,
        file_path=path,
    )


def main(argv: list[str]) -> int:
    """Decode a binary log file to text."""
    if len(argv) != 2:
        print("Usage: python -m interfaces.obc_gs_interface.logging.log_codec <binary-log-file>", file=sys.stderr)
        return 1
    for entry in decode_log_stream(Path(argv[1]).read_bytes()):
        print(entry_to_text(entry))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))